config/routes.rb
Rails.application.routes.draw do
  resources :applies do
    resources :ratings, only: [:new, :create, :edit, :update]
  end
  resources :ratings
  resources :festivals do
    # patch 'actualizar_estado_postulacion', on: :member
    resources :applies
    member do
      get 'terms', to: 'festivals#terms'
      get 'send_terms_notification'
      patch 'actualizar_estado_postulacion/:apply_id', to: 'festivals#actualizar_estado_postulacion', as: 'actualizar_estado_postulacion'
   
    end
  end
  get 'home/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  namespace :admin do
   
    get 'dashboard', to: 'dashboard#index'
    resources :festivals do
      get 'assign_organizers', on: :collection
      post 'enviar_correo_a_participantes', on: :member
      post 'enviar_correo_a_rechazados', on: :member
      post 'assign_organizers', on: :collection, to: 'festivals#process_assign_organizers'
      
      member do
        post 'assign_organizers', to: 'festivals#assign_organizers'
        get 'editar_estado_postulacion', to: 'festivals#editar_estado_postulacion'
        patch 'actualizar_estado_postulacion', to: 'festivals#actualizar_estado_postulacion'
        get 'personas_que_quedaron', to: 'festivals#personas_que_quedaron'

      
      end
      collection do
        get 'assign_organizers' # Define la ruta para la acción assign_organizers
        get 'seleccionar_festival'
      end
      put :close_applications
      put :close_festival
    end
    resources :festival_organizers
    
  end

  namespace :jurado do
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :usuario do
    get 'dashboard', to: 'dashboard#index'
    get 'dashboard/applies', to: 'dashboard#applies'
    get "user/profile/:name", to: 'dashboard#profile', as: :user_profile
    get 'user/edit/profile/:name', to: 'dashboard#edit', as: :user_profile_edit
  
  end

  namespace :organizador do
    get 'dashboard', to: 'dashboard#index'
    get 'dashboard/applies', to: 'dashboard#applies'
    get 'dashboard/ranking', to: 'dashboard#ranking'
  end
  # Definir la ruta root según el rol del usuario
  root 'home#dashboard_redirect'

end

app/models/admin/festival_organizer.rb
# == Schema Information
#
# Table name: admin_festival_organizers
#
#  id          :bigint           not null, primary key
#  festival_id :bigint           not null
#  user_id     :bigint           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Admin::FestivalOrganizer < ApplicationRecord
  belongs_to :festival
  belongs_to :user
end

app/controllers/admin/festival_organizers_controller.rb
class Admin::FestivalOrganizersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_admin_festival_organizer, only: %i[ show edit update destroy ]
  layout "admin_layout"
  # GET /admin/festival_organizers or /admin/festival_organizers.json
  def index
    @admin_festival_organizers = Admin::FestivalOrganizer.all
  end

  # GET /admin/festival_organizers/1 or /admin/festival_organizers/1.json
  def show
  end

  # GET /admin/festival_organizers/new
  def new
    @admin_festival_organizer = Admin::FestivalOrganizer.new
  end

  # GET /admin/festival_organizers/1/edit
  def edit
  end

  # POST /admin/festival_organizers or /admin/festival_organizers.json
  def create
    @festival = Festival.find(admin_festival_organizer_params[:festival_id])
    @admin_festival_organizer = @festival.admin_festival_organizers.build(admin_festival_organizer_params.except(:festival_id))

    respond_to do |format|
      if @admin_festival_organizer.save
        @admin_festival_organizer.user.update(role: "Organizador")
        format.html { redirect_to admin_festival_organizer_url(@admin_festival_organizer), notice: "Festival organizer was successfully created." }
        format.json { render :show, status: :created, location: @admin_festival_organizer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_festival_organizer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/festival_organizers/1 or /admin/festival_organizers/1.json
  def update
    respond_to do |format|
      if @admin_festival_organizer.update(admin_festival_organizer_params)
        format.html { redirect_to admin_festival_organizer_url(@admin_festival_organizer), notice: "Festival organizer was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_festival_organizer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_festival_organizer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/festival_organizers/1 or /admin/festival_organizers/1.json
  def destroy
    @admin_festival_organizer.destroy

    respond_to do |format|
      format.html { redirect_to admin_festival_organizers_url, notice: "Festival organizer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_festival_organizer
      @admin_festival_organizer = Admin::FestivalOrganizer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_festival_organizer_params
      params.require(:admin_festival_organizer).permit(:festival_id, :user_id)
    end
end

app/helpers/admin/festival_organizers_helper.rb
module Admin::FestivalOrganizersHelper
end

app/views/admin/festival_organizers/_festival_organizer.html.erb
<div id="<%= dom_id festival_organizer %>">
  <p>
    <strong>Festival:</strong><br>

    <%= festival_organizer.festival.name %>
    <%= festival_organizer.festival.year %>

  </p>

  <p>
    <strong>User:</strong><br>
    <%= festival_organizer.user.name %>
  </p>

</div>

app/views/admin/festival_organizers/_form.html.erb
<%= form_with(model: admin_festival_organizer) do |form| %>
  <% if admin_festival_organizer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin_festival_organizer.errors.count, "error") %> prohibited this admin_festival_organizer from being saved:</h2>

      <ul>
        <% admin_festival_organizer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div>
    <%= form.label :festival_id, style: "display: block" %>
    <%= form.collection_select :festival_id, Festival.all.where(state: true), :id, :name, { prompt: 'Select festival' }, { class: 'form-select' } %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <input type="text" id="myInput" placeholder="Buscar organizadores...">
    <%= form.collection_select :user_id, User.all, :id, :email, { prompt: 'Select organizer' }, { class: 'form-select' ,id: 'mySelect'} %>
  </div>

  <div class="text-end">
    <%= form.submit class:"btn btn-primary my-2", value:"Asignar Organizador" %>
  </div>
<% end %>



<script>
// Obtener el campo de entrada y el menú desplegable
var input = document.getElementById('myInput');
var select = document.getElementById('mySelect');

// Agregar un controlador de eventos para el evento keyup en el campo de entrada
input.addEventListener('keyup', function() {
  // Obtener el valor del campo de entrada y convertirlo a mayúsculas
  var filter = input.value.toUpperCase();
  // console.log(filter)
  // Obtener todas las opciones del menú desplegable
  var options = select.getElementsByTagName('option');

  // Recorrer todas las opciones del menú desplegable
  for (var i = 0; i < options.length; i++) {
    // Obtener el texto de la opción actual
    var txtValue = options[i].textContent || options[i].innerText;

    // Si el texto de la opción coincide con el filtro, mostrar la opción, de lo contrario, ocultarla
    if (txtValue.toUpperCase().indexOf(filter) > -1) {
      options[i].style.display = '';
    } else {
      options[i].style.display = 'none';
    }
  }
});
</script>

app/views/admin/festival_organizers/edit.html.erb
<h1>Editing festival organizer</h1>

<%= render "form", admin_festival_organizer: @admin_festival_organizer %>

<br>

<div>
  <%= link_to "Show this festival organizer", @admin_festival_organizer %> |
  <%= link_to "Back to festival organizers", admin_festival_organizers_path %>
</div>

app/views/admin/festival_organizers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Festival organizers</h1>

<div id="admin_festival_organizers">
  <% @admin_festival_organizers.each do |admin_festival_organizer| %>
    <%= render admin_festival_organizer %>
    <p>
      <%= link_to "Show this festival organizer", admin_festival_organizer %>
    </p>
  <% end %>
</div>

<%= link_to "New festival organizer", new_admin_festival_organizer_path %>

app/views/admin/festival_organizers/new.html.erb
<h1>New festival organizer</h1>

<%= render "form", admin_festival_organizer: @admin_festival_organizer %>

<br>

<div>
  <%= link_to "Back to festival organizers", admin_festival_organizers_path %>
</div>

app/views/admin/festival_organizers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @admin_festival_organizer %>

<div>
  <%= link_to "Edit this festival organizer", edit_admin_festival_organizer_path(@admin_festival_organizer) %> |
  <%= link_to "Back to festival organizers", admin_festival_organizers_path %>

  <%= button_to "Destroy this festival organizer", @admin_festival_organizer, method: :delete %>
</div>