config/routes.rb
Rails.application.routes.draw do
  resources :applies do
    resources :ratings, only: [:new, :create, :edit, :update]
  end
  resources :ratings
  resources :festivals do
    # patch 'actualizar_estado_postulacion', on: :member
    resources :applies
    member do
      get 'terms', to: 'festivals#terms'
      get 'send_terms_notification'
      patch 'actualizar_estado_postulacion/:apply_id', to: 'festivals#actualizar_estado_postulacion', as: 'actualizar_estado_postulacion'
   
    end
  end
  get 'home/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  namespace :admin do
   
    get 'dashboard', to: 'dashboard#index'
    resources :festivals do
      get 'assign_organizers', on: :collection
      post 'enviar_correo_a_participantes', on: :member
      post 'enviar_correo_a_rechazados', on: :member
      post 'assign_organizers', on: :collection, to: 'festivals#process_assign_organizers'
      
      member do
        post 'assign_organizers', to: 'festivals#assign_organizers'
        get 'editar_estado_postulacion', to: 'festivals#editar_estado_postulacion'
        patch 'actualizar_estado_postulacion', to: 'festivals#actualizar_estado_postulacion'
        get 'personas_que_quedaron', to: 'festivals#personas_que_quedaron'

      
      end
      collection do
        get 'assign_organizers' # Define la ruta para la acción assign_organizers
        get 'seleccionar_festival'
      end
      put :close_applications
      put :close_festival
    end
    resources :festival_organizers
    
  end

  namespace :jurado do
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :usuario do
    get 'dashboard', to: 'dashboard#index'
    get 'dashboard/applies', to: 'dashboard#applies'
    get "user/profile/:name", to: 'dashboard#profile', as: :user_profile
    get 'user/edit/profile/:name', to: 'dashboard#edit', as: :user_profile_edit
  
  end

  namespace :organizador do
    get 'dashboard', to: 'dashboard#index'
    get 'dashboard/applies', to: 'dashboard#applies'
    get 'dashboard/ranking', to: 'dashboard#ranking'
  end
  # Definir la ruta root según el rol del usuario
  root 'home#dashboard_redirect'

end

app/models/festival.rb
# == Schema Information
#
# Table name: festivals
#
#  id                   :bigint           not null, primary key
#  name                 :string           not null
#  year                 :integer          not null
#  state                :boolean          default(TRUE)
#  application_state    :boolean          default(TRUE)
#  user_id              :bigint           not null
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  description          :text
#  country              :string
#  terms_and_conditions :text             default("Términos y condiciones por defecto.")
#
class Festival < ApplicationRecord
  # validaciones
  validates :name, presence: true
  validates :year, presence: true  
  validates :description, presence: true
  validates :country, presence: true
  
  #  Relaciones 
  belongs_to :user
  #Relaciones a muchos
  has_many :applies, dependent: :destroy
  has_many :organizerships
  
  # relaciones muchos a muchos
  has_many :organizerships
  has_many :organizers, through: :organizerships, source: :user
  has_many :admin_festival_organizers, class_name: 'Admin::FestivalOrganizer'
  
  has_many :festival_organizers, through: :admin_festival_organizers, source: :user



  # ... otras asociaciones y validaciones ...

  
  # Relaciones a active storage
  has_one_attached :festival_logo


  def ranking
    self.applies
        .left_joins(:ratings)
        .group('applies.id')
        .select('applies.*, COALESCE(AVG(ratings.stars), 0) AS avg_stars')
        .order('avg_stars DESC')
  end
end

app/controllers/admin/festivals_controller.rb
class Admin::FestivalsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_festival, only: [:show, :edit, :update, :destroy,:process_assign_organizers]
    layout "admin_layout"
    def close_applications
        @festival = Festival.find(params[:festival_id])
        @festival.update(application_state: false)
        redirect_to admin_festival_path(@festival), notice: "Postulaciones cerradas"
    end

    def close_festival
        @festival = Festival.find(params[:festival_id])
        if @festival.update(state: false)
          # Cambiar el rol de los organizadores a "Usuario"
          @festival.admin_festival_organizers.each do |organizer|
            organizer.user.update(role: "Usuario")
          end
      
          redirect_to admin_festival_path(@festival), notice: "Festival cerrado y roles de organizadores cambiados a usuarios."
        else
          redirect_to admin_festival_path(@festival), alert: "Error al cerrar el festival."
        end
    end
    
    def assign_organizers
        @festivals = current_user.festivals.where(state: true)
    end
    def show
    end
    
    def process_assign_organizers
      @festival = Festival.find(params[:festival_id])

      @user_ids = params[:user_ids]
      
      if @user_ids.present?
        @festival.organizers << User.where(id: @user_ids)
        redirect_to admin_festival_path(@festival), notice: 'Organizadores asignados exitosamente.'
      else
        redirect_to admin_festival_path(@festival), alert: 'Debes seleccionar al menos un usuario.'
      end
  
      
    end
    def editar_estado_postulacion
      @festival = Festival.find(params[:id])
   @applies = @festival.applies.where(terms_and_conditions_accepted: true)
    @postulantes = User.all.pluck(:name)
      
    end
    
    def actualizar_estado_postulacion
      @festival = Festival.find(params[:id])
      @apply = Apply.find(params[:apply_id])
    
      if @apply.update(quedo_en_festival: true)
        redirect_to admin_festival_path(@festival), notice: 'Estado de postulación actualizado correctamente.'
      else
        Rails.logger.error(@apply.errors.inspect) # Esto registrará los errores en el registro de Rails.
   
        redirect_to admin_festival_path(@festival), alert: 'Estado de postulación no se actualizado correctamente.'
      end
    end
    
    
    def seleccionar_festival
      @festivales_activos = Festival.where(state: true)
    end

    def personas_que_quedaron
      @festival = Festival.find_by(state: true) # Obtener el festival activo basado en el atributo `state`
      if @festival
        @personas_que_quedaron = @festival.applies
                                  .where(quedo_en_festival: true)
                                  .includes(:user)
                                  

      else
        @personas_que_quedaron = [] # Si no hay festival activo, establecer la lista como vacía o manejar de acuerdo a tu lógica
      end
    end   
    
    def enviar_correo_a_participantes
      @festival = Festival.find(params[:id])
      @participantes = @festival.applies.where(quedo_en_festival: true).includes(:user).map(&:user)
      
      @participantes.each do |participante|
        # Aquí puedes llamar a un método o servicio para enviar el correo electrónico.
        # Por ejemplo, si estás usando Action Mailer en Rails, puedes llamar a un correo electrónico definido previamente.
        # Reemplaza 'CorreoParticipanteMailer' y 'correo_participante' con tus propias clases y métodos.
        UserMailer.correo_participante(participante, @festival).deliver_now
      end
      
      redirect_to admin_festival_path(@festival), notice: 'Correo electrónico enviado a todos los participantes.'
    end
    def enviar_correo_a_rechazados
      @festival = Festival.find(params[:id])
      @participantes = @festival.applies.where(quedo_en_festival: false).includes(:user).map(&:user)
      
      @participantes.each do |participante|
        # Aquí puedes llamar a un método o servicio para enviar el correo electrónico.
        # Por ejemplo, si estás usando Action Mailer en Rails, puedes llamar a un correo electrónico definido previamente.
        # Reemplaza 'CorreoParticipanteMailer' y 'correo_participante' con tus propias clases y métodos.
        UserMailer.correo_rechazados(participante, @festival).deliver_now
      end
      
      redirect_to admin_festival_path(@festival), notice: 'Correo electrónico enviado a todos los participantes.'
    end

      private
    
      def set_festival
        @festival = Festival.find(params[:id])
      end
      def apply_params
        params.require(:apply).permit(:quedo_en_festival,:festival_id,:apply_id)
      end
     
end

app/controllers/festivals_controller.rb
class FestivalsController < ApplicationController
  before_action :authenticate_user!
  layout :set_layout
  before_action :set_festival, only: %i[ show edit update destroy ]
  load_and_authorize_resource
  # GET /festivals or /festivals.json
  def index
    @festivals = Festival.all
  end

  # GET /festivals/1 or /festivals/1.json
  def show
    @festival=Festival.find(params[:id])
  end

  # GET /festivals/new
  def new
    @festival = current_user.festivals.build
  end

  # GET /festivals/1/edit
  def edit
  end

  # POST /festivals or /festivals.json
  def create
    @festival = current_user.festivals.build(festival_params)

    respond_to do |format|
      if @festival.save
        format.html { redirect_to festival_url(@festival), notice: "Festival was successfully created." }
        format.json { render :show, status: :created, location: @festival }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @festival.errors, status: :unprocessable_entity }
      end
    end
  end
  # envio de correos para aceptar terminos y condiciones 

  def send_terms_notification
    @festival = Festival.find(params[:id])
    @applications_without_accepted_terms = @festival.applies.where(terms_and_conditions_accepted: false)

    @applications_without_accepted_terms.each do |application|
      # Enviar correo a cada aplicación pendiente de aceptación
      UserMailer.terms_notification_email(application, application.user, @festival).deliver_now
    end

    redirect_to root_path, notice: "Se ha enviado una notificación para aceptar los términos y condiciones."
  end

  # PATCH/PUT /festivals/1 or /festivals/1.json
  def update
    respond_to do |format|
      if @festival.update(festival_params)
        format.html { redirect_to festival_url(@festival), notice: "Festival was successfully updated." }
        format.json { render :show, status: :ok, location: @festival }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @festival.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /festivals/1 or /festivals/1.json
  def destroy
    @festival.destroy

    respond_to do |format|
      format.html { redirect_to festivals_url, notice: "Festival was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def terms
    @festival = Festival.find(params[:id])
  end

  def close_applications
    @festival = Festival.find(params[:id])
    @festival.update(application_state: false)
    redirect_to admin_festival_path(@festival), notice: "Postulaciones cerradas"
  end

  def close_festival
      @festival = Festival.find(params[:id])
      @festival.update(state: false)
      redirect_to admin_festival_path(@festival), notice: "Festival cerrado"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_festival
      @festival = Festival.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def festival_params
      params.require(:festival).permit(:name, :year, :state, :application_state, :user_id,:festival_logo, :description, :country, :terms_and_conditions)
    end
    def set_layout
      case current_user.role
      when 'Admin'
        'admin_layout'
      when 'Jurado'
        authorize! :read, Festival # Por ejemplo, el jurado solo puede leer (ver) los festivales
        'jurado_layout'
      when 'Usuario'
        authorize! :read, Festival # Por ejemplo, el usuario solo puede leer (ver) los festivales
        'user_layout'
      when 'Organizador'
        authorize! :manage, Festival # Por ejemplo, el organizador puede gestionar (crear, editar, eliminar) los festivales
        'organizador_layout'
      else
        # Si el rol del usuario no coincide con ninguno de los casos anteriores, utiliza el diseño predeterminado
        'application'
      end
    end
end

app/helpers/admin/festivals_helper.rb
module Admin::FestivalsHelper
end

app/helpers/festivals_helper.rb
module FestivalsHelper
end

app/views/admin/festivals/_enviar_correo_a_participantes.html.erb
<%= form_tag enviar_correo_a_participantes_admin_festival_path(@festival), method: :post do %>
  <div class="form-group">
    <%= submit_tag 'Enviar Correo Electrónico a Participantes', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/festivals/_enviar_correo_a_rechazados.html.erb
<%= form_tag enviar_correo_a_rechazados_admin_festival_path(@festival), method: :post do %>
  <div class="form-group">
    <%= submit_tag 'Enviar Correo Electrónico a Rechazados', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/festivals/assign_organizers.html.erb
<h1>Asignar Organizadores</h1>

<%= form_tag(processassign_organizers_admin_festivals_path(@festival), method: :post) do %>
  <div class="form-group">
  <label for="festival_id">Seleccionar Festival:</label>
  <%= collection_select(nil, :festival_id, @festivals, :id, :name, { prompt: 'Seleccionar festival' }, { class: 'form-select select2 select2-festival' })  %>
  
</div>

  <div class="form-group">
    <label for="organizer_ids">Seleccionar Organizadores:</label>
    <input type="text" id="myInput" placeholder="Buscar organizadores...">
    <%= collection_select(nil, :organizer_ids, User.all, :id, :email, { prompt: 'Seleccionar organizadores' }, { class: 'form-select select2 select2-organizer', id: 'mySelect' }) %>
  </div>
  <div class="form-group text-end">
    <%= submit_tag 'Asignar organizadores', class: 'btn btn-primary' %>
  </div>
<% end %>









<script>
// Obtener el campo de entrada y el menú desplegable
var input = document.getElementById('myInput');
var select = document.getElementById('mySelect');

// Agregar un controlador de eventos para el evento keyup en el campo de entrada
input.addEventListener('keyup', function() {
  // Obtener el valor del campo de entrada y convertirlo a mayúsculas
  var filter = input.value.toUpperCase();
  // console.log(filter)
  // Obtener todas las opciones del menú desplegable
  var options = select.getElementsByTagName('option');

  // Recorrer todas las opciones del menú desplegable
  for (var i = 0; i < options.length; i++) {
    // Obtener el texto de la opción actual
    var txtValue = options[i].textContent || options[i].innerText;

    // Si el texto de la opción coincide con el filtro, mostrar la opción, de lo contrario, ocultarla
    if (txtValue.toUpperCase().indexOf(filter) > -1) {
      options[i].style.display = '';
    } else {
      options[i].style.display = 'none';
    }
  }
});
</script>

app/views/admin/festivals/editar_estado_postulacion.html.erb
<%= form_tag actualizar_estado_postulacion_admin_festival_path(@festival), method: :patch do %>
  <div class="form-group">
    <%= label_tag :apply_id, 'Seleccionar Postulante:' %>
    <%= select_tag :apply_id, options_for_select(@applies.map { |apply| [apply.name, apply.id] }), prompt: 'Seleccione un postulante', class: 'form-select select2' %>
  </div>
  
  <!-- Resto de tu formulario aquí -->

  <div class="form-group text-end">
    <%= submit_tag 'Seleccionar Participante', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/festivals/personas_que_quedaron.html.erb
<!-- En app/views/admin/festivals/personas_que_quedaron.html.erb -->
<h1>Personas que Quedaron en el Festival</h1>
<div class="d-flex justify-content-end">

  <%= render 'admin/festivals/enviar_correo_a_participantes' %>
</div>

<table class="table table-bordered border-primary">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Email</th>
      <th>Nombre Artístico</th>
      <th>acto</th>
      <th>telefono</th>
    </tr>
  </thead>
  <tbody>
        
        <% if @personas_que_quedaron != [] %>
            
    
        
        <% @personas_que_quedaron.each do |apply| %>
        <tr>
            <td><%= apply.user.name %></td>
            <td><%= apply.user.email %></td>
            <td><%= apply.name %></td>
            <td><%= apply.act %></td>
            <td><%= apply.user.phone_number %></td>
        </tr>
        

        <% end %>
    <% else  %>
        <p>Aún no hay participantes seleccionados</p>
    <% end %>
    
  </tbody>
</table>



<% if @festival %>
  <%= link_to 'Seleccionar Participantes', editar_estado_postulacion_admin_festival_path(@festival), class: 'btn btn-primary mt-3' %>
<% end %>
<br>
<%= link_to 'Volver al Festival', admin_festival_path(@festival) %>


<div class="d-flex justify-content-end">

  <%= render 'admin/festivals/enviar_correo_a_rechazados' %>
</div>

app/views/admin/festivals/seleccionar_festival.html.erb
<!-- En app/views/admin/festivals/seleccionar_festival.html.erb -->
<h1>Seleccionar Festival Activo</h1>

<% if @festivales_activos.any? %>
  <p>Por favor, selecciona un festival activo:</p>
  <ul>
    <% @festivales_activos.each do |festival| %>
      <li>
        <%= link_to festival.name, personas_que_quedaron_admin_festival_path(festival), class: 'btn btn-primary' %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No hay festivales activos disponibles.</p>
<% end %>

<%= link_to 'Volver al Dashboard', admin_dashboard_path %>

app/views/admin/festivals/show.html.erb
<h1>Festival Details</h1>
<p>Name: <%= @festival.name %></p>
<p>Organizers:</p>
<ul>