config/routes.rb
Rails.application.routes.draw do
  resources :applies do
    resources :ratings, only: [:new, :create, :edit, :update]
  end
  resources :ratings
  resources :festivals do
    # patch 'actualizar_estado_postulacion', on: :member
    resources :applies
    member do
      get 'terms', to: 'festivals#terms'
      get 'send_terms_notification'
      patch 'actualizar_estado_postulacion/:apply_id', to: 'festivals#actualizar_estado_postulacion', as: 'actualizar_estado_postulacion'
   
    end
  end
  get 'home/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  namespace :admin do
   
    get 'dashboard', to: 'dashboard#index'
    resources :festivals do
      get 'assign_organizers', on: :collection
      post 'enviar_correo_a_participantes', on: :member
      post 'enviar_correo_a_rechazados', on: :member
      post 'assign_organizers', on: :collection, to: 'festivals#process_assign_organizers'
      
      member do
        post 'assign_organizers', to: 'festivals#assign_organizers'
        get 'editar_estado_postulacion', to: 'festivals#editar_estado_postulacion'
        patch 'actualizar_estado_postulacion', to: 'festivals#actualizar_estado_postulacion'
        get 'personas_que_quedaron', to: 'festivals#personas_que_quedaron'

      
      end
      collection do
        get 'assign_organizers' # Define la ruta para la acción assign_organizers
        get 'seleccionar_festival'
      end
      put :close_applications
      put :close_festival
    end
    resources :festival_organizers
    
  end

  namespace :jurado do
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :usuario do
    get 'dashboard', to: 'dashboard#index'
    get 'dashboard/applies', to: 'dashboard#applies'
    get "user/profile/:name", to: 'dashboard#profile', as: :user_profile
    get 'user/edit/profile/:name', to: 'dashboard#edit', as: :user_profile_edit
  
  end

  namespace :organizador do
    get 'dashboard', to: 'dashboard#index'
    get 'dashboard/applies', to: 'dashboard#applies'
    get 'dashboard/ranking', to: 'dashboard#ranking'
  end
  # Definir la ruta root según el rol del usuario
  root 'home#dashboard_redirect'

end

app/controllers/organizador/dashboard_controller.rb
class Organizador::DashboardController < ApplicationController
  include Pagy::Backend
  before_action :authenticate_user!
  layout "organizador_layout"  
  def index
    @user = current_user
    @festival_organizer = Admin::FestivalOrganizer.find_by(user_id: @user.id)
    
    if @festival_organizer
      @festival = @festival_organizer.festival
      @total_postulaciones = Apply.where(festival_id: @festival.id).count
      @total_calificadas = Rating.joins(apply: :festival)
                         .where(festivals: { id: @festival.id })
                         .where(ratings: { user_id: current_user.id })
                         .count

      @postulaciones_por_categoria = Apply.where(festival_id: @festival.id).group(:category_id).count
    end
    
    # @user = current_user
    # @organized_festivals = @user.organized_festivals


  end
  def applies
    response.headers['X-Content-Type-Options'] = 'nosniff'
    @user = current_user
    @festival_organizer = Admin::FestivalOrganizer.find_by(user_id: @user.id)
    if @festival_organizer
      @festival = @festival_organizer.festival
      @pagy ,@applies= pagy(@festival.applies, items: 10)
      
    # Obtener todas las calificaciones del usuario actual para las postulaciones cargadas
    @ratings = Rating.where(apply_id: @applies.pluck(:id), user_id: @user.id)
    
    # Crear un hash para mapear el rating de cada postulación
    @ratings_hash = @ratings.group_by(&:apply_id).transform_values { |rating| rating.first.stars }

    end
  end
  def ranking
    @user = current_user
    @festival_organizer = Admin::FestivalOrganizer.find_by(user_id: @user.id)
    if @festival_organizer
      @festival = @festival_organizer.festival
    @ranking_applies = @festival.ranking
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_festival_organizer
      @admin_festival_organizer = Admin::FestivalOrganizer.find(params[:id])
    end
end

app/helpers/organizador/dashboard_helper.rb
module Organizador::DashboardHelper
end

app/views/organizador/shared/_calificacion.html.erb
<div class="rating">
  <div class="star">★</div>
  
  <% if rating==0 %>
    <div class="rating-value">Aun no has calificado esta Postulacion</div>
  <%else%>  
  <div class="rating-value-bold"><%= rating %></div>
  <% end %>
  
</div>

app/views/organizador/shared/_card_metricas.html.erb
<div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-<%=color%> shadow h-100 py-2">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-<%=color%> text-uppercase mb-1">
                       Postulaciones <%=text%></div>
                    <div class="h5 mb-0 font-weight-bold text-gray-800"><%=count%></div>
                </div>
                <div class="col-auto">
                    <i class="fas fa-calendar fa-2x text-gray-300"></i>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/organizador/shared/_card_postulaciones_revisadas.html.erb
<div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-<%=color%> shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-<%=color%> text-uppercase mb-1"><%=text%> = <%=total_calificadas%>
                        </div>
                        <div class="row no-gutters align-items-center">
                            <div class="col-auto">
                                <div class="h5 ml-2  mr-3 font-weight-bold text-gray-800"> <% porcentaje= ((total_calificadas.to_f/total_postulaciones)*100).round%><%=porcentaje%>%</div>
                            </div>
                            <div class="col">
                                <div class="progress progress-sm mr-2">
                                    <div class="progress-bar bg-info" role="progressbar"
                                        style="width: <%=porcentaje%>%" aria-valuenow="50" aria-valuemin="0"
                                        aria-valuemax="100"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

app/views/organizador/shared/_sidebar.html.erb
   <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon ">
                     <%= image_tag 'logo_circo.png' ,style:"width:50px;", class:"ml-3"%>
                    <%# <i class="fa-solid fa-tent"></i> %>
                </div>
                <div class="sidebar-brand-text mx-3">Festivapp</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <%= link_to  root_path, class:"nav-link" do %>
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                <% end %>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Mi festival
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <%= link_to  organizador_dashboard_applies_path, class:"nav-link collapsed" do %>
                
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Postulaciones</span>
                
                
                <% end %>
                
                
            </li>
            <li class="nav-item">
                <%= link_to  organizador_dashboard_ranking_path, class:"nav-link collapsed" do %>
                
                    <i class="fa-solid fa-ranking-star"></i>
                    <span>Ranking</span>
                
                
                <% end %>
                
                
            </li>

           <br><br><br><br><br><br><br><br><br>

            

     
            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block mb-5">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline mt-5">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

            <!-- Sidebar Message -->
            

        </ul>
        <!-- End of Sidebar -->

       

app/views/organizador/shared/_topbar.html.erb
<!-- Topbar -->
<nav class="navbar  navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <%# <!-- Topbar Search -->
    <form
        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form> %> <!-- Sidebar - Brand -->
 

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
<%# 
        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small"
                            placeholder="Search for..." aria-label="Search"
                            aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li> %>

   
        <%# <!-- Nav Item - Alerts -->
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">3+</span>
            </a>
            <!-- Dropdown - Alerts -->
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                    Alerts Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-primary">
                            <i class="fas fa-file-alt text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">December 12, 2019</div>
                        <span class="font-weight-bold">A new monthly report is ready to download!</span>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-success">
                            <i class="fas fa-donate text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">December 7, 2019</div>
                        $290.29 has been deposited into your account!
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-warning">
                            <i class="fas fa-exclamation-triangle text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">December 2, 2019</div>
                        Spending Alert: We've noticed unusually high spending for your account.
                    </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
            </div>
        </li> %>

    
        <div class="topbar-divider d-none d-sm-block"></div>
<!-- Default dropstart button -->
    <div class=" btn-group dropdown">
        <button type="button" class="nav-link btn btn-transparent  no-arrow dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%=current_user.name%></span>
                <% if current_user.avatar.present? %>
                            <%= image_tag current_user.avatar.variant(resize_to_fill: [50, 50]) ,class:"img-profile rounded-circle"%>
                <% else %>
                    <i class="fa-solid fa-circle-user img-profile rounded-circle"></i>
                <% end %> 
        </button>



        <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
            <!--<li><button class="dropdown-item" type="button"><i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                        Activity Log</button></li>-->
            <li><%= link_to  usuario_user_profile_path(current_user.name) ,class:"dropdown-item" do%>
               
                
                        <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                        Perfil
                    
                    <% end %>
                    
            </li>
            <li>
                <%= button_to  destroy_user_session_path, method: :delete, class:"dropdown-item" do %>
                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                Cerrar Sesión

                
                <% end %>
            </li>
        </ul>
    </div>

</nav>
<!-- End of Topbar -->