config/routes.rb
Rails.application.routes.draw do
  resources :applies do
    resources :ratings, only: [:new, :create, :edit, :update]
  end
  resources :ratings
  resources :festivals do
    # patch 'actualizar_estado_postulacion', on: :member
    resources :applies
    member do
      get 'terms', to: 'festivals#terms'
      get 'send_terms_notification'
      patch 'actualizar_estado_postulacion/:apply_id', to: 'festivals#actualizar_estado_postulacion', as: 'actualizar_estado_postulacion'
   
    end
  end
  get 'home/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  namespace :admin do
   
    get 'dashboard', to: 'dashboard#index'
    resources :festivals do
      get 'assign_organizers', on: :collection
      post 'enviar_correo_a_participantes', on: :member
      post 'enviar_correo_a_rechazados', on: :member
      post 'assign_organizers', on: :collection, to: 'festivals#process_assign_organizers'
      
      member do
        post 'assign_organizers', to: 'festivals#assign_organizers'
        get 'editar_estado_postulacion', to: 'festivals#editar_estado_postulacion'
        patch 'actualizar_estado_postulacion', to: 'festivals#actualizar_estado_postulacion'
        get 'personas_que_quedaron', to: 'festivals#personas_que_quedaron'

      
      end
      collection do
        get 'assign_organizers' # Define la ruta para la acción assign_organizers
        get 'seleccionar_festival'
      end
      put :close_applications
      put :close_festival
    end
    resources :festival_organizers
    
  end

  namespace :jurado do
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :usuario do
    get 'dashboard', to: 'dashboard#index'
    get 'dashboard/applies', to: 'dashboard#applies'
    get "user/profile/:name", to: 'dashboard#profile', as: :user_profile
    get 'user/edit/profile/:name', to: 'dashboard#edit', as: :user_profile_edit
  
  end

  namespace :organizador do
    get 'dashboard', to: 'dashboard#index'
    get 'dashboard/applies', to: 'dashboard#applies'
    get 'dashboard/ranking', to: 'dashboard#ranking'
  end
  # Definir la ruta root según el rol del usuario
  root 'home#dashboard_redirect'

end

app/models/rating.rb
# == Schema Information
#
# Table name: ratings
#
#  id         :bigint           not null, primary key
#  stars      :integer
#  apply_id   :bigint           not null
#  user_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Rating < ApplicationRecord
  # Validaciones 
  validates :stars , presence: true
  validates :user_id, presence: true
  validates :apply_id, uniqueness: { scope: :user_id, message: "Ya has calificado esta postulación" }

  # Realciones 
  belongs_to :apply
  belongs_to :user

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: %i[ show edit update destroy ]

  # GET /ratings or /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1 or /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    
    @apply = Apply.find(params[:apply_id])
    @rating = @apply.ratings.build
    @rating.user = curent_user
  end

  # GET /ratings/1/edit
  def edit
    # @rating = Rating.find(params[:id]) # Cargar la calificación existente
  end

  # POST /ratings or /ratings.json
  def create
   
    @apply = Apply.find(params[:apply_id])
    @rating = @apply.ratings.build(rating_params)
    @rating.user = current_user
   
    respond_to do |format|
      if @rating.save
        format.html { redirect_to festival_apply_path(@rating.apply.festival, @rating.apply), notice: "Calificación hecha con éxito"
        }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1 or /ratings/1.json
  def update
    puts "llegue aqui"
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to festival_apply_path(@rating.apply.festival, @rating.apply), notice: "Calificación actualizada con éxito"
        }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1 or /ratings/1.json
  def destroy
    @rating.destroy

    respond_to do |format|
      format.html { redirect_to ratings_url, notice: "Rating was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rating_params
      params.require(:rating).permit(:stars, :apply_id, :user_id)
    end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_edit_form.html.erb
<%= form_with(model: [@apply, @rating], url: apply_rating_path(@apply, @rating), method: :patch) do |form| %>
 

  <% if form.object.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(form.object.errors.count, "error") %> prohibited this rating from being saved:</h2>
      <ul>
        <% form.object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label "Editar calificación", style: "display: block ", class: "form-label" %>
  <div class="d-flex justify-content-between">
    
    <div class="star-rating" id="star-rating" value="<%= @rating.stars %>">
    <% (1..10).each do |i| %>
      <span class="fa fa-star" name="rating[stars]" value="<%= i %>"></span>
    <% end %>
  </div>
  <%= form.hidden_field :stars, value: @rating.stars %>

    <%= form.submit 'calificar' ,class:"btn btn-primary"%>
  </div>
<% end %>

<script>
  document.addEventListener("DOMContentLoaded", function () {
  const starRatingElement = document.getElementById("star-rating");
  const stars = starRatingElement.querySelectorAll(".fa-star");
  let ratingValue = parseInt(document.getElementById('star-rating').getAttribute('value'));
  console.log(ratingValue);
   updateStars(ratingValue);

  stars.forEach((star, index) => {
    const starValue = index + 1;

    star.addEventListener("click", function () {
      ratingValue = starValue;
      updateStars(ratingValue);
    });
  });

  function updateStars(ratingValue) {
    stars.forEach((star, index) => {
      const starValue = index + 1;
      
      if (starValue <= ratingValue) {
        star.classList.add("checked");
      } else {
        star.classList.remove("checked");
      }
    });
    // Actualiza el campo oculto con el valor seleccionado
      document.getElementById('rating_stars').value =ratingValue;
   
  }

 
});



</script>

app/views/ratings/_form.html.erb
<%= form_with(model: @apply.ratings.build,id:"new_apply" ,url: apply_ratings_path(@apply)) do |form| %>
  <% if form.object.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(form.object.errors.count, "error") %> prohibited this rating from being saved:</h2>
      <ul>
        <% form.object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

   <%= form.label "Editar calificación", style: "display: block ", class: "form-label" %>
  <div class="d-flex justify-content-between">
    
    <div class="star-rating" id="star-rating" value="0">
    <% (1..10).each do |i| %>
      <span class="fa fa-star" name="rating[stars]" value="<%= i %>"></span>
    <% end %>
  </div>
  <%= form.hidden_field :stars, value: 0 %>

    <%= form.submit 'calificar' ,class:"btn btn-primary"%>
  </div>
<% end %>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const starRatingElement = document.getElementById("star-rating");
  const stars = starRatingElement.querySelectorAll(".fa-star");
  let ratingValue = parseInt(document.getElementById('star-rating').getAttribute('value'));
  console.log(ratingValue);
   updateStars(ratingValue);

  stars.forEach((star, index) => {
    const starValue = index + 1;

    star.addEventListener("click", function () {
      console.log("estoy aqui");

      ratingValue = starValue;
      console.log(ratingValue);
      updateStars(ratingValue);
    });
  });

  function updateStars(ratingValue) {
    stars.forEach((star, index) => {
      const starValue = index + 1;
      
      if (starValue <= ratingValue) {
        star.classList.add("checked");
      } else {
        star.classList.remove("checked");
      }
    });
    // Actualiza el campo oculto con el valor seleccionado
      document.getElementById('rating_stars').value =ratingValue;
   
  }

 
});



</script>

app/views/ratings/_rating.html.erb
<div id="<%= dom_id rating %>">
  <p>
    <strong>Stars:</strong>
    <%= rating.stars %>
  </p>

  <p>
    <strong>Apply:</strong>
    <%= rating.apply_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= rating.user_id %>
  </p>

</div>

app/views/ratings/edit.html.erb
<h1>Editing rating</h1>

<%= render "form", rating: @rating %>

<br>

<div>
  <%= link_to "Show this rating", @rating %> |
  <%= link_to "Back to ratings", ratings_path %>
</div>

app/views/ratings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ratings</h1>

<div id="ratings">
  <% @ratings.each do |rating| %>
    <%= render rating %>
    <p>
      <%= link_to "Show this rating", rating %>
    </p>
  <% end %>
</div>

<%= link_to "New rating", new_rating_path %>

app/views/ratings/new.html.erb
<h1>New rating</h1>

<%= render "form", rating: @rating %>

<br>

<div>
  <%= link_to "Back to ratings", ratings_path %>
</div>

app/views/ratings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @rating %>

<div>
  <%= link_to "Edit this rating", edit_rating_path(@rating) %> |
  <%= link_to "Back to ratings", ratings_path %>

  <%= button_to "Destroy this rating", @rating, method: :delete %>
</div>